### register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "something@a.com",
    "password": "test"
}


### login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "test"
}

### logout

POST http://localhost:3000/auth/logout
Content-Type: application/application/json

{
    "email": "a@a.com",
    "password": "test"
}


### Dogs breeds

GET https://dog.ceo/api/breeds/list/all

### Get comments

GET http://localhost:3000/comments/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTlmMDMyNzE4ODRmNDBiNTc5YjU3YzkiLCJpYXQiOjE3MDQ5MjIyOTQsImV4cCI6MTcwNDkyNTg5NH0._B-R-3NBJX9Nv9N3dc9Cg61GIG53Q9SVYa3yviJp9Zk

