### register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "a@a.com",
    "password": "test"
}


### login

POST http://localhost:3000/auth/login
Content-Type: application/application/json

{
    "username": "a@a.com",
    "password": "test"
}

### logout

POST http://localhost:3000/auth/logout
Content-Type: application/application/json

{
    "username": "a@a.com",
    "password": "test"
}


### Dogs breeds

GET https://dog.ceo/api/breeds/list/all


